# Generated by Django 4.1.7 on 2023-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electornics', 'Electronics'), ('motors', 'Motors'), ('fashion', 'Fashion'), ('collectibles', 'Collectibles and Art'), ('sports', 'Sports'), ('health', 'Health and Beauty'), ('industrial', 'Industrial Equipment'), ('home', 'Home and Garden')], max_length=64),
        ),
    ]
