# Generated by Django 4.1.7 on 2023-04-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electornics', 'Electronics'), ('motors', 'Motors'), ('fashion', 'Fashion'), ('collectibles', 'Collectibles and Art'), ('sports', 'Sports'), ('health', 'Health and Beauty'), ('industrial', 'Industrial Equipment'), ('home', 'Home and Garden'), (None, 'None')], default=None, max_length=64),
        ),
    ]
