# Generated by Django 4.1.7 on 2023-04-04 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_listing_bids_bid_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listing',
            new_name='listing_id',
        ),
    ]
