# Generated by Django 4.1.7 on 2023-04-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_remove_comment_item_comment_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('', 'Choose Category'), ('electronics', 'Electronics'), ('motors', 'Motors'), ('fashion', 'Fashion'), ('collectibles', 'Collectibles and Art'), ('sports', 'Sports'), ('health', 'Health and Beauty'), ('industrial', 'Industrial Equipment'), ('home', 'Home and Garden')], max_length=64, null=True),
        ),
    ]
